export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_STOP = "AUTH_STOP";

export const LOGOUT = "LOGOUT";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";

export const ASYNC_STARTED = "ASYNC_STARTED";
export const ASYNC_ENDED = "ASYNC_ENDED";
export const SET_ACTION_CONFIRMATION = "SET_ACTION_CONFIRMATION";
export const SET_ACTION_CONFIRMATION_PROGRESS =
  "SET_ACTION_CONFIRMATION_PROGRESS";
export const SET_ACTION_CONFIRMATION_RESULT = "SET_ACTION_CONFIRMATION_RESULT";
export const ACTION_CONFIRMED = "ACTION_CONFIRMED";
export const CHANGE_EDITED_PROJECT = "CHANGE_EDITED_PROJECT";
