export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_STOP = "AUTH_STOP";

export const LOGOUT = "LOGOUT";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";

export const ASYNC_STARTED = "ASYNC_STARTED";
export const ASYNC_ENDED = "ASYNC_ENDED";
